name: Build and Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from CMake
        id: get_version
        shell: pwsh
        run: |
          $version = Select-String -Path CMakeLists.txt -Pattern 'project\(HueSyncStudio VERSION (.+?) LANGUAGES' | ForEach-Object { $_.Matches.Groups[1].Value }
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          echo "Detected version: $version"

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
        shell: cmd

      - name: Cache vcpkg artifacts
        uses: actions/cache@v4
        with:
          path: |
            vcpkg/installed
            vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-direct-${{ hashFiles('.github/workflows/build_and_release.yml') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-direct-

      # Direkte Installation ohne Manifest-Modus
      - name: Install dependencies
        run: |
          .\vcpkg\vcpkg.exe install qtbase qtwebsockets qt5-declarative qt5-quickcontrols2 spdlog nlohmann-json catch2 rtaudio --triplet=x64-windows
        shell: cmd

      - name: Configure CMake
        run: |
          cmake -B build -S . ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake ^
            -DBUILD_TESTING=ON ^
            -DVCPKG_TARGET_TRIPLET=x64-windows
        shell: cmd

      - name: Build project
        run: |
          cmake --build build --config Release --parallel
        shell: cmd

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure -C Release
        shell: cmd

      - name: Package artifacts
        run: |
          cmake --build build --config Release --target package || echo "Package step encountered issues but continuing..."
        shell: pwsh

      - name: List all build artifacts
        run: |
          Write-Host "===== Build directory content ====="
          Get-ChildItem -Path "build" -Recurse -Depth 2 | Select-Object FullName, Length | Format-Table -AutoSize
          
          Write-Host "===== CPack outputs ====="
          Get-ChildItem -Path "build/_CPack_Packages" -Recurse -Include "*.exe","*.msi","*.nsis" -ErrorAction SilentlyContinue | Select-Object FullName, Length
          Get-ChildItem -Path "build" -Include "*.exe","*.msi","*.zip" -ErrorAction SilentlyContinue | Select-Object FullName, Length
        shell: pwsh

      - name: Create ZIP archive
        run: |
          # Mögliche Orte für die ausführbaren Dateien
          $possibleBuildDirs = @(
            "build/Release",
            "build/bin/Release",
            "build/src/Release"
          )
          
          $exeFiles = $null
          $buildDir = $null
          
          foreach ($dir in $possibleBuildDirs) {
            if (Test-Path $dir) {
              $exeFiles = Get-ChildItem -Path $dir -Filter "*.exe" -Recurse -ErrorAction SilentlyContinue
              if ($exeFiles) {
                $buildDir = $dir
                break
              }
            }
          }
          
          if (-not $buildDir) {
            Write-Host "Searching for executables in the entire build directory..."
            $exeFiles = Get-ChildItem -Path "build" -Filter "*.exe" -Recurse -ErrorAction SilentlyContinue | 
                        Where-Object { -not $_.FullName.Contains("vcpkg") -and -not $_.FullName.Contains("_deps") }
            
            if ($exeFiles) {
              $mainExe = $exeFiles | Where-Object { $_.Name -eq "HueSyncStudio.exe" -or $_.Name -like "*HueSyncStudio*.exe" } | Select-Object -First 1
              if ($mainExe) {
                $buildDir = Split-Path -Parent $mainExe.FullName
              } else {
                $buildDir = Split-Path -Parent $exeFiles[0].FullName
              }
            }
          }
          
          if (-not $buildDir) {
            Write-Host "ERROR: Could not find any executables in build directories"
            exit 0  # Continue workflow to upload any available artifacts
          }
          
          Write-Host "Found build directory with executables: $buildDir"
          
          $version = "${{ steps.get_version.outputs.VERSION }}"
          $zipName = "HueSyncStudio-$version-Win64.zip"
          
          # Sammle alle relevanten Dateien
          $filesToZip = @()
          $filesToZip += Get-ChildItem -Path $buildDir -Filter "*.exe" -Recurse | Select-Object -ExpandProperty FullName
          $filesToZip += Get-ChildItem -Path $buildDir -Filter "*.dll" -Recurse | Select-Object -ExpandProperty FullName
          
          if ($filesToZip.Count -gt 0) {
            Compress-Archive -Path $filesToZip -DestinationPath "build/$zipName" -Force
            Write-Host "Created ZIP archive: build/$zipName with $($filesToZip.Count) files"
          } else {
            Write-Host "Warning: No files found to include in ZIP"
          }
        shell: pwsh

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          files: |
            build/*.exe
            build/*.zip
            build/*.msi
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('v{0}', steps.get_version.outputs.VERSION) }}
          name: HueSyncStudio ${{ steps.get_version.outputs.VERSION }}
          generate_release_notes: true
