name: Build and Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies
        run: |
          .\vcpkg\vcpkg.exe install qtbase qtwebsockets spdlog nlohmann-json catch2 rtaudio --recurse

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake -DBUILD_TESTING=ON

      - name: Build project
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Package artifacts
        run: cmake --build build --config Release --target package || true

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.zip
          tag_name: v${{ github.run_number }}
          name: HueSyncStudio Release ${{ github.run_number }}
